module.exports.pages = {
  NOT_FOUND_PAGE: 'pages/loggedOut/404',
  SERVER_ERROR_PAGE: 'pages/loggedIn/500',
  CONFIG_LIVE_PAGE: 'pages/loggedIn/live',
  MANAGE_ADMINS_PAGE: 'pages/loggedIn/manage-admins',
  CREATE_ADMIN_PAGE: 'pages/loggedIn/create-admin',
  MANAGE_MEDIA_PAGE: 'pages/loggedIn/manage-media',
  CREATE_MEDIA_PAGE: 'pages/loggedIn/create-media',
  UPDATE_MEDIA_PAGE: 'pages/loggedIn/update-media',
  MANAGE_SCHEDULE_PAGE: 'pages/loggedIn/manage-schedule',
  CREATE_SCHEDULE_PAGE: 'pages/loggedIn/create-schedule',
  MANAGE_BIOS_PAGE: 'pages/loggedIn/manage-bios',
  CREATE_BIO_PAGE: 'pages/loggedIn/create-bio',
  LOGIN_PAGE: 'pages/loggedOut/login',
  SEND_RESET_PAGE: 'pages/loggedOut/send-reset',
  RESET_PW_PAGE: 'pages/loggedOut/reset-password',
};
