module.exports.pages = {
  NOT_FOUND_PAGE: 'pages/loggedOut/404',
  CONFIG_LIVE_PAGE: 'pages/loggedIn/live',
  MANAGE_ADMINS_PAGE: 'pages/loggedIn/manage-admins',
  CREATE_ADMIN_PAGE: 'pages/loggedIn/create-admin',
  MANAGE_VIDEOS_PAGE: 'pages/loggedIn/manage-videos',
  CREATE_VIDEO_PAGE: 'pages/loggedIn/create-video',
  UPDATE_VIDEO_PAGE: 'pages/loggedIn/update-video',
  MANAGE_TRACKS_PAGE: 'pages/loggedIn/manage-tracks',
  CREATE_TRACK_PAGE: 'pages/loggedIn/create-track',
  UPDATE_TRACK_PAGE: 'pages/loggedIn/update-track',
  LOGIN_PAGE: 'pages/loggedOut/login',
  SEND_RESET_PAGE: 'pages/loggedOut/send-reset',
  RESET_PW_PAGE: 'pages/loggedOut/reset-password',
};
